
```{r}
library(tidyverse)
library(gganimate)
library(gifski)
```


```{r}
df <- read.csv("C:/Users/Harsh/Desktop/Sem6/AI/Project2.2/allegations.csv")
df %>% head()
```



```{r}
df_temp <- df %>% 
  select(year_received, allegation = fado_type, result = board_disposition) %>%
  mutate(result = case_when(
    str_detect(result, "Substantiated") ~ "Violation", 
    str_detect(result, "Exonerated") ~ "Violation",
    TRUE ~ "No_violation"
  )) %>%
  group_by(year_received) %>%
  count(allegation, result) %>%
  ungroup()

df_temp
```




```{r}
df %>% 
  select(year_received, allegation = fado_type, result = board_disposition) %>%
  mutate(result = case_when(
    str_detect(result, "Substantiated") ~ "Violation", 
    str_detect(result, "Exonerated") ~ "Violation",
    TRUE ~ "No_violation"
  )) %>%
  group_by(year_received) %>%
  count(allegation, result) %>%
  ungroup() %>%
  ggplot(aes(x = year_received, y = n, color = allegation)) +
  geom_line() + 
  facet_wrap(~result, scales = "free_y") +
  theme(legend.position = "top")
```


```{r}
df %>% 
  select(year_received, allegation = fado_type, result = board_disposition) %>%
  mutate(result = case_when(
    str_detect(result, "Substantiated") ~ "Violation", 
    str_detect(result, "Exonerated") ~ "Violation",
    TRUE ~ "No_violation"
  )) %>%
  group_by(year_received) %>%
  count(allegation, result) %>%
  ungroup() %>%
  ggplot(aes(x = year_received, y = n, color = allegation)) +
  geom_line() + 
  geom_point() +
  facet_wrap(~result, scales = "free_y") + 
  theme(legend.position = "top") +
  transition_reveal(year_received)
```


```{r}
df_temp <- df %>%
    select(year_received, result = board_disposition) %>%
    mutate(result = case_when(
        str_detect(result, "Substantiated") ~ "Violation", 
        str_detect(result, "Exonerated") ~ "Violation", 
        TRUE ~ "No_violation"
    )) %>%
    count(year_received, result)

df_temp
```



```{r}
df %>%
    select(year_received, result = board_disposition) %>%
    mutate(result = case_when(
        str_detect(result, "Substantiated") ~ "Violation",
        str_detect(result, "Exonerated") ~ "Violation",
        TRUE ~ "No_violation"
    )) %>%
    count(year_received, result) %>% 
    ggplot(aes(x = result, y = n, fill = result)) +
    geom_col() +
    theme(legend.position = "none") + 
    transition_time(year_received) +
    labs(title = "Year: {frame_time}")
```



```{r}
df %>% 
  select(precinct, unique_mos_id, allegation = fado_type) %>%
  group_by(precinct) %>%
  count(unique_mos_id, allegation) %>%
  ungroup() 
```




```{r}
df %>% 
  select(precinct, unique_mos_id, allegation = fado_type) %>%
  group_by(precinct) %>%
  count(unique_mos_id, allegation) %>%
  ungroup() %>%
  ggplot(aes(x = n, fill = allegation)) +
  geom_histogram() + 
  theme(legend.position = "top")
```




```{r}
df %>% 
  select(precinct, unique_mos_id, allegation = fado_type) %>%
  group_by(precinct) %>%
  count(unique_mos_id, allegation) %>%
  ungroup() %>%
  ggplot(aes(x = n, fill = allegation)) +
  geom_histogram() + 
  theme(legend.position = "none") +
  facet_wrap(~allegation, scales = "free_y")
```




```{r}
df %>% 
  select(precinct, unique_mos_id, allegation = fado_type) %>%
  group_by(precinct) %>%
  count(unique_mos_id, allegation) %>%
  ungroup() %>%
  ggplot(aes(x = n, fill = allegation)) +
  geom_histogram() + 
  theme(legend.position = "none") +
  facet_wrap(~allegation, scales = "free_y") +
  transition_states(precinct, 
                    transition_length = 15, 
                    state_length = 2) +
  labs(title = "Precinct: {closest_state}") +
  enter_fade() +
  exit_shrink()
```



```{r}
df %>%
  select(rank_incident, year_received, result = board_disposition) %>%
  mutate(result = case_when(
        str_detect(result, "Substantiated") ~ "Violation",
        str_detect(result, "Exonerated") ~ "Violation",
        TRUE ~ "No_violation"
    )) %>%
  group_by(year_received, rank_incident) %>%
  count(rank_incident, result) %>%
  ungroup() %>%
  pivot_wider(names_from = result, values_from = n, values_fill = 0)
```




```{r}
df %>%
  select(rank_incident, year_received, result = board_disposition) %>%
  mutate(result = case_when(
        str_detect(result, "Substantiated") ~ "Violation",
        str_detect(result, "Exonerated") ~ "Violation",
        TRUE ~ "No_violation"
    )) %>%
  group_by(year_received, rank_incident) %>%
  count(rank_incident, result) %>%
  ungroup() %>%
  pivot_wider(names_from = result, values_from = n, values_fill = 0) %>%
  ggplot(aes(x = No_violation, y = Violation, color = rank_incident)) +
  geom_point() + 
  theme(legend.position = "top") +
  geom_abline(slope = 1, intercept = 0) 
  
```



```{r}
df %>%
  select(rank_incident, year_received, result = board_disposition) %>%
  mutate(result = case_when(
        str_detect(result, "Substantiated") ~ "Violation",
        str_detect(result, "Exonerated") ~ "Violation",
        TRUE ~ "No_violation"
    )) %>%
  group_by(year_received, rank_incident) %>%
  count(rank_incident, result) %>%
  ungroup() %>%
  pivot_wider(names_from = result, values_from = n, values_fill = 0) %>%
  ggplot(aes(x = No_violation, y = Violation, color = rank_incident)) +
  geom_point(size = 6) + 
  geom_abline(slope = 1, intercept = 0) +
  theme(legend.position = "top") +
  transition_time(year_received) +
  shadow_wake(wake_length = .1) +
  labs(title = "Year: {frame_time}", 
       subtitle = "\nPoints below the line means \nmajority of allegations are false
       \nPoints above the line means\nmajority of allegations are true\n")
```

